  
# 核心任务

- name: oracle
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
  
  

  roles:
    - {role: role_common, tags: "role_common"}  
    - {role: role_jdk, tags: "role_jdk"}  
    - {role: oracle, tags: "oracle"}
    - {role: role_preend, tags: "preend"}
   # - {role: role_end, tags: "role_end"}
