# install by OS family
#- name: Install this role on {{ansible_os_family}}
 # include: "{{ansible_os_family}}.yml"

# configure oracle

- name: Add oracle User
  user:
    name: oracle
    shell: /usr/sbin/login

- name: Create oracle directory
  file:
    path: /data/wwwroot/oracle
    state: directory
    owner: oracle
    group: oracle

- name: Create the storage directory for files.
  file:
      path: /opt/oracle/data
      state: directory 
      owner: oracle 
      group: oracle
      mode: g+w
          

#- name: Add oracle repositories 
 ####yum_repository:
 #   name: oracle
 #   description: oracle yum repo
  #  file: yum.repos.d
  #  baseurl: http://public-yum.oracle.com/public-yum-ol7.repo
  ###  gpgcheck: no
  


- name: Download oracle
  get_url:
    url: https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-18c-1.0-1.x86_64.rpm  
    dest: /root
    mode: '0440'
         

- name: Install oracle
  shell: yum -y localinstall oracle-database-xe-18c-1.0-1.x86_64.rpm    

# oracle configuration
- name: Set password
  shell: (echo {{oracle_db_password}}; echo {{oracle_db_password}};) | /etc/init.d/oracle-xe-18c configure


- name: Set the environment
  shell: |
    su - oracle 
    echo "export ORACLE_BASE=/opt/oracle"  >> ~/.bash_profile
    echo  "export ORACLE_HOME=/opt/oracle/product/18c/dbhomeXE" >> ~/.bash_profile
    echo "export ORACLE_SID=XE"  >> ~/.bash_profile
    echo "export PATH=$PATH:$ORACLE_HOME/bin"  >> ~/.bash_profile
    source  ~/.bash_profile


- name: Set soft link 
  shell: ln -sf /etc/systemd/system/oracle-xe-18c.service  /etc/systemd/system/oracle.service


- name: Restart oracle.service
  service:
    name: oracle.service
    state: restarted
    enabled: yes












# set soft link, -b cover the exist links
# ln -sf src des
- name: set soft link
  shell: |
    ln -sf /opt/oracle  /data/wwwroot
    ln -sf /opt/oracle/config /data/config
    ln -sf /opt/oracle/cfgtoollogs/dbca/XE   /data/logs
    

# Check version,
# must use sudo sh -c to solve the no-root permission
- block:
  - name: Check oracle Version
    shell: sudo sh -c "oraclectl status | grep 'oracle version' 1>> /data/logs/install_version.txt"



# check service state
- name: Check oracle Service     
  shell: systemctl status oracle | grep Active*
  register: check_oracle_service
  notify: check_oracle_service
