

# configure oracle

- name: Create oracle User
  user:
    name: oracle
    shell: /usr/sbin/nologin
    home: /data/wwwroot/oracle
    create_home: no

- name: Create oracle directory
  file:
    path: /data/wwwroot/oracle
    state: directory
    owner: oracle
    group: oracle

- name: Create the storage directory for files.
  file:
      path: /opt/oracle/data
      state: directory 
      owner: oracle 
      group: oracle
      mode: g+w
          

#- name: Add oracle repositories 
 #yum_repository:
 #   name: oracle
 #   description: oracle yum repo
  #  file: yum.repos.d
  #  baseurl: http://public-yum.oracle.com/public-yum-ol7.repo
  #  gpgcheck: no
  


- name: install oracle
  shell: 
        wget https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-18c-1.0-1.x86_64.rpm 
         

- name: install oracle
  shell: yum localinstall oracle-database-xe-18c-1.0-1.x86_64.rpm


# oracle configuration
- name: Set password
  shell: (echo "password"; echo "password";) | /etc/init.d/oracle-xe-18c configure


- name: start and enable oracle service
  shell: |
          systemctl daemon-reload
          systemctl start oracle-xe-18c
          /sbin/chkconfig oracle-xe-18c on

- name: /etc/hosts 
  lineinfile:
         dest:  /etc/hosts
         line: '0.0.0.0 localhost'

- name: 
  lineinfile:
         dest:  /opt/oracle/product/18c/dbhomeXE/network/admin/tnsnames.ora
         regexp: '^HOST='
         line: 'HOST= 0.0.0.0'



- name: Restart oracle.service
  service:
    name: oracle-xe-18c.service
    state: restarted
    enabled: yes












# set soft link, -b cover the exist links
# ln -sf src des
- name: set soft link
  shell: |
    ln -sf /opt/oracle  /data/wwwroot
    ln -sf /opt/oracle/config /data/config
    ln -sf /opt/oracle/cfgtoollogs/dbca/XE   /data/logs

# Check version,
# must use sudo sh -c to solve the no-root permission
- block:
  - name: Check oracle Version
    shell: sudo sh -c "oraclectl status | grep 'oracle version' 1>> /data/logs/install_version.txt"



# check service state
- name: Check oracle Service     
  shell: systemctl status oracle | grep Active*
  register: check_oracle_service
  notify: check_oracle_service
