
 
# install ORACLE by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml" 

- name: Download oracle
  get_url:
    url: https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-18c-1.0-1.x86_64.rpm
    dest: /root

- name: Install oracle
  shell: 
    cmd: yum -y localinstall oracle-database-xe-18c-1.0-1.x86_64.rpm
    chdir: /root

# Oracle configuration
- name: Set 
  shell: (echo {{oracle_db_password}}; echo {{oracle_db_password}};) | /etc/init.d/oracle-xe-18c configure

      


- name: change to oracle
  shell: su oracle

- name: set database directory
  blockinfile:
    path: /home/oracle/.bash_profile
    owner: oracle
    block: |
      export ORACLE_BASE=/opt/oracle 
      export ORACLE_HOME=/opt/oracle/product/18c/dbhomeXE
      export ORACLE_SID=XE
      export PATH=$PATH:$ORACLE_HOME/bin

- name: source ok
  shell: source /home/oracle/.bash_profile
# Rename oracle service and  restart oracle



- name: Reload service
  shell: systemctl daemon-reload



- name: Rename service
  shell:   ln -sf /run/systemd/generator.late/oracle-xe-18c.service    /run/systemd/generator.late/oracle.service


- name: Restart oracle.service
  service:
    name: oracle.service
    state: restarted
    enabled: yes
   
- name: Create oracle directory
  file:
    path: /data/root/oracle
    state: directory
  


- name: set soft link
  shell: |
    ln -sf /opt/oracle  /data/root
    ln -sf /opt/oracle/config /data/config
    ln -sf /opt/oracle/cfgtoollogs/dbca/XE   /data/logs
    

# check service state
- name: Check oracle Service     
  shell: systemctl status oracle | grep Active*
  register: check_oracle_service
  notify: check_oracle_service
 
# Check version,
# must use sudo sh -c to solve the no-root permission
- name: check version
  shell: sudo sh -c "echo ` rpm -qa |grep oracle-database-xe` “>> /data/logs/install_version.txt"