tasks:
  - name: "Preinstall oracle"
    command: curl -o oracle-database-preinstall-18c-1.0-1.el7.x86_64.rpm https://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/getPackage/oracle-database-preinstall-18c-1.0-1.el7.x86_64.rpm
    when: ansible_facts['os_family'] == "Redhat"


     