---
- name: Install MySQL
  apt:  
    name: [mysql-server,python-pymysql]

- name: Change MySQL Directory
  shell: |
    systemctl stop mysql
    rsync -av /var/lib/mysql /data/
    mv /var/lib/mysql /var/lib/mysql.bak
    mkdir /var/lib/mysql/mysql -p
    sed  -i 's/\/var\/lib\/mysql/\/data\/mysql/'  /etc/mysql/mysql.conf.d/mysqld.cnf
    echo "alias /var/lib/mysql/ -> /data/mysql/," >> /etc/apparmor.d/tunables/alias
    systemctl restart apparmor
    systemctl start mysql

- name: Change MySQL root user password 
  mysql_user: 
    name: root 
    host: localhost
    password: "{{mysql_root_password | default('Websoft9',true)}}"

- name: Removes all anyelse user accounts
  mysql_user:
    login_user: root
    login_password: "{{mysql_root_password | default('Websoft9',true)}}"
    name: ''
    host_all: yes
    state: absent

- name: Remove hostname user accounts
  mysql_user: login_user=root login_password={{mysql_root_password | default('Websoft9',true)}} name='root' host={{ ansible_nodename }} state=absent

- name: Removes test Databases
  mysql_db:
    login_user: root
    login_password: "{{mysql_root_password | default('Websoft9',true)}}"
    name: test
    state: absent

- name: Removing privileges on test database
  command: mysql -uroot -p{{mysql_root_password | default('Websoft9',true)}} -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"

- name: del mysql Automatically generated for Debian scripts.
  file:
    path: /etc/mysql/debian.cnf
    state: absent


- name: Create a MySQL  symbolic link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: '/etc/mysql/mysql.conf.d/mysqld.cnf',dest: /data/config/mysqld.cnf}  
    - {src: '/var/log/mysql',dest: '/data/logs/mysqld'}
