- name: Import Node.js Repo
  shell: curl -sL https://deb.nodesource.com/setup_{{nodejs_ver}}.x | sudo -E bash -

- name: Install build tools
  apt:
    name: build-essential
    update_cache: yes


- name: Install Node.js
  apt:
    name: nodejs
    update_cache: yes
    
- name:  Add yarn an Apt signing key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name:  Import yarn repo
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    filename: yarn

- name: Install Yarn
  apt:
    name: yarn
    update_cache: true
   