- name: Add the PPA
  apt_repository:
    repo: ppa:brightbox/ruby-ng

- name: Install Ruby
  apt:
    name: ['ruby{{ruby_version}}','ruby{{ruby_version}}-dev']

# 此处gem模块安装命令会带版本号,且命令所带版本号和命令实际版本号不一致,后期待修复,暂用shell模块安装
- name: Install Bundler 
  shell: gem install bundler


  
    